<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Arch.System.SourceGenerator" Version="2.1.0" />
        <PackageReference Include="Arch" Version="2.1.0" />
        <PackageReference Include="Arch.EventBus" Version="1.0.2" />
        <PackageReference Include="Arch.System" Version="1.1.0" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\UmbrashiftECS.Components\UmbrashiftECS.Components.csproj" />
      <ProjectReference Include="..\UmbrashiftECS.Operations\UmbrashiftECS.Operations.csproj" />
    </ItemGroup>
</Project>
