<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\UmbrashiftECS.Components\UmbrashiftECS.Components.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Arch">
        <HintPath>..\..\..\..\.nuget\packages\arch\2.1.0-beta\lib\net8.0\Arch.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
